file_format: "1"
id: charybdis
name: Charybdis
type: shield
url: https://github.com/Bastardkb/Charybdis/
requires: [nice_nano_v2]
features:
  - keys
  - pointer
siblings:
  - charybdis_left
  - charybdis_right